# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: repoplace-registry-sls-api

plugins:
  - serverless-offline

# Configuration variables
custom:
  secrets: ${file(secrets.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.jwtSecret}

# The `functions` block defines what code to deploy
functions:
  authorize:
    handler: api/postAuthorize.handler
    events:
      - http:
          path: api/post/authorize
          method: post
          cors: true
  public:
    handler: api/getPublic.handler
    events:
      - http:
          path: api/get/public
          method: get
          cors: true
          # authorizer: authorize # Cats are public
  protected:
    handler: api/getProtected.handler
    events:
      - http:
          path: api/get/protected
          method: get
          cors: true
          authorizer: authorize # Pangolins are protected
  testLogin: #no authorizer required, accepts username/password instead of jwt
    handler: tests/login-mock-users/login.handler 
    events:
      - http:
          path: api/test/post/login
          method: post
          cors: true 